### ISSUE TITLE
Fails to update AssemblyInfo arguments that have spaces between the quotes and parenthesese

### ISSUE THREAD

**Issue by mrbedo** [BMuuN/vsts-assemblyinfo-task#1]
For example this gets updated by the addin:
`[assembly: AssemblyDescription("My default description")]`
This doesn't
`[assembly: AssemblyDescription( "My default description" )]`

The difference is the space between `(` and `"`

Otherwise seems to work great!

**Comment by BMuuN** [comment]
Fixed with PR #4
