### ISSUE TITLE
Auto detect encoding seems to fail if files have different encodings.

### ISSUE THREAD

**Issue by xMonkfish** [BMuuN/vsts-assemblyinfo-task#100]
Hi

The logs below show some odd behaviour where it seems that the task is trying to use the encoding from the previous file to process subsequent files which results in a failure if the encoding does not match. I took a brief glimpse at the source and that doesn't seem like it should be possible if the encoding is set to auto which has confused me completely.

Any idea what I've done wrong here?

Many thanks

David

----------------
Task         : Assembly Info (.Net Core & .Net Standard)
Description  : Set assembly or package information such as Version, Copyright and Repository URL's etc.
Version      : 2.0.73
Author       : Bleddyn Richards
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)

Task Parameters...
	Source folder: d:\a\1\s
	Source files: **/*.csproj
	Insert attributes: true
	File encoding: auto
	Write unicode BOM: true
	Generate NuGet package on build: false
	Require license acceptance: false
	Package id: 
	Package version: 
	Authors: 
	Company: 
	Product: 
	Description: 
	Copyright: 
	License Url: 
	Project Url: 
	Icon Url: 
	Repository Url: 
	Repository type: 
	Tags: 
	Release notes: 
	Assembly neutral language: 
	Assembly version: 1.1.0.0
	Assembly file version: 1.1.0.0
	Informational version: 1.1.0-alpha.19+Branch.dev.Sha.f49f1ae27752169f7bbafb96750f5bb4810bb840

Setting .Net Core / .Net Standard assembly info...
Processing: d:\a\1\s\DatabaseUpgrade\Upgrade\MetadataUpgrade\MetadataUpgrade.csproj
	Detected character encoding: iso-8859-2
	GeneratePackageOnBuild --> false
	PackageRequireLicenseAcceptance --> false
	AssemblyVersion --> 1.1.0.0
	FileVersion --> 1.1.0.0
	InformationalVersion --> 1.1.0-alpha.19+Branch.dev.Sha.f49f1ae27752169f7bbafb96750f5bb4810bb840
	Verify character encoding: iso-8859-2

Processing: d:\a\1\s\LFS.API.Management\LFS.API.Management.csproj
	Detected character encoding: iso-8859-2
	GeneratePackageOnBuild --> false
	PackageRequireLicenseAcceptance --> false
	AssemblyVersion --> 1.1.0.0
	FileVersion --> 1.1.0.0
	InformationalVersion --> 1.1.0-alpha.19+Branch.dev.Sha.f49f1ae27752169f7bbafb96750f5bb4810bb840
	Verify character encoding: iso-8859-2

Processing: d:\a\1\s\LFS.Gateway.Api.Common\LFS.Gateway.Api.Common.csproj
	Detected character encoding: utf-8
	Detected character encoding (utf-8) is different to the one specified (iso-8859-2).
##[error]Error reading file: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: ď

**Comment by BMuuN** [comment]
Fixed in v2.1.91
