### ISSUE TITLE
Support for AndroidManifest.xml

### ISSUE THREAD

**Issue by PhilPJL** [BMuuN/vsts-assemblyinfo-task#102]
Is it possible you could add support for setting the android:versionCode and android:versionName properties in AndroidManifest.xml?  This xml file is in the properties folder of an Android app next to the AssemblyInfo.  If it makes a difference I'm creating a Xamarin forms app.

Ideally (for me) android:versionName would be the same as AssemblyVersion, e.g. $(Build.BuildNumber) like "2019.08.12.1" and android:versionCode would be derived from that, in this case 2019081201.  This would conform to the max allowed versionCode of 2100000000.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="2" android:versionName="1.0.0.0" package="com.my.app" android:installLocation="internalOnly">
	<uses-sdk android:minSdkVersion="27" android:targetSdkVersion="28" />
	<application android:label="MyApp" android:icon="@drawable/layersTripleOutline"></application>
</manifest>
```

**Comment by ChrisTTian667** [comment]
that would be very helpful for me too.

**Comment by BMuuN** [comment]
There are currently no plans to add support for XML files however I am curious...

Does the [Google Play](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play) task not populate these values for you? or could you utilise the wonderful [XDT Transform](https://marketplace.visualstudio.com/items?itemName=qetza.xdttransform) task by @qetza?

**Comment by BMuuN** [comment]
Closing as there are no plans to implement support for Android Manifest files at this time.
