### ISSUE TITLE
Pipeline variables not used for Assembly Info

### ISSUE THREAD

**Issue by ChrisLeeBare** [BMuuN/vsts-assemblyinfo-task#103]
Hello,
thank you for this great task!
But somehow our pipeline variables are not used.

![image](https://user-images.githubusercontent.com/7479364/64243504-c0ed2b00-cf07-11e9-8f5d-e57bedcda978.png)

This results in:
![image](https://user-images.githubusercontent.com/7479364/64243545-d3fffb00-cf07-11e9-81fd-8387767efcc6.png)

The pipeline variables have values set. In the wiki I could not find any hint on pipeline variables.

Regards

**Comment by BMuuN** [comment]
Can't say I've come across this issue.  Can you ensure you're running the latest version of the extension (v2.1.91) and let me know if your issue is affected by the Net Core or Net Framework task?

**Comment by ChrisLeeBare** [comment]
Hi,

yes I am running this version:
![image](https://user-images.githubusercontent.com/7479364/72251376-19db7700-35fe-11ea-8949-d239e6a4bd30.png)

**Comment by BMuuN** [comment]
Just spotted what your issue is: - you're using curly brackets `{} `and not regular brackets `()`. If you change your variables to the following it'll work:
```
$(boe.moduleid)
$(boe.moduleProductName)
```
