### ISSUE TITLE
Option to fail build if no AssemblyInfo is updated

### ISSUE THREAD

**Issue by gghart** [BMuuN/vsts-assemblyinfo-task#104]
Once thing we've noticed using this extension is that unlike pretty much everything else you put in the build or release pipeline, if it "fails", it returns success and keeps going. This has lead to a few instances where we released files with the wrong metadata.

Ideally, we would like to see a change so that if the extension is run and no source files are found, the result returned is set to error and it breaks the build at that point. If at least 1 source file found to modify, it returns success.

This would mean that if you messed up the Source folder/file list, or it was moved/changed at some point, the build would fail and you'd know you need to fix something.

**Comment by BMuuN** [comment]
Fixed with #145.  Will be released with v3.0.x
