### ISSUE TITLE
AssemblyInformationalVersion

### ISSUE THREAD

**Issue by sheepnerd** [BMuuN/vsts-assemblyinfo-task#106]
Azure DevOps Server 2019 creating simple WFP app. 
**The plugin dont write AssemblyInformationalVersion field.**

[AssemblyInfo.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/3757112/AssemblyInfo.log)

**Comment by BMuuN** [comment]
@sheepnerd you don't have the `[assembly: AssemblyInformationalVersion("")]` attribute in you `AssemblyInfo.cs` file.  Either add this attribute or from the task enable the `Insert attributes` option.
