### ISSUE TITLE
Allow other file such as Build.props for .net core

### ISSUE THREAD

**Issue by godefroyo** [BMuuN/vsts-assemblyinfo-task#116]
We use Directory.Build.props to sync assemblies on the same version. It would be nice to be able to update a .props file 😃

**Comment by IanMercer** [comment]
I was getting impatient waiting for this PR so I cloned your branch and pushed up my own private azure devops extension and then started hacking on it. My conclusion after experimenting for a while was **that this should be its own separate task** and not be mixed in with the net framework and net core tasks; it's really quite different. For instance, when you have a `shared.msbuild` file it is already a single central place where you can set the author, company and all those other properties. All you really need when you have a shared msbuild/props file is a way to update _the fields that change_ during a build, i.e. the version information and maybe the copyright message (date). So in my version I stripped the code right back to just those properties. I also decided that for a shared msbuild/props file there may be multiple `PropertyGroup` elements, so I decided to examine all of them and only update properties that are already present (simplifying things further and removing another option).  I would offer this up as an alternative PR to this one, but I had some issues building the project the way it is currently configured (node_modules not in task folder, don't seem to be included in vsix output).

![image](https://user-images.githubusercontent.com/347540/80163822-33407780-858c-11ea-9f58-88a9946b6f31.png)
