### ISSUE TITLE
ApplicationInsights throw timeouts if Buildserver has no internet access

### ISSUE THREAD

**Issue by mrksmhr** [BMuuN/vsts-assemblyinfo-task#119]
Hello,
my builds break since the update to 2.1.91.
The reason for this is the addition of ApplicationInsights.
Can you provide a way to turn off the ApplicationInsights?

To the background:
Our build server has no internet access.

ApplicationInsights:Sender [ 'Ingestion endpoint could not be reached 5 consecutive times. There may be resulting telemetry loss. Most recent error:',
  { Error: connect ETIMEDOUT 13.69.66.140:443
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '13.69.66.140',
    port: 443 } ]
ApplicationInsights:Sender [ 'Ingestion endpoint could not be reached 10 consecutive times. There may be resulting telemetry loss. Most recent error:',
  { Error: connect ETIMEDOUT 13.69.65.22:443
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '13.69.65.22',
    port: 443 } ]
ApplicationInsights:Sender [ 'Ingestion endpoint could not be reached 15 consecutive times. There may be resulting telemetry loss. Most recent error:',
  { Error: connect ETIMEDOUT 13.69.66.140:443
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '13.69.66.140',
    port: 443 } ]

**Comment by maikhanns** [comment]
We have the same problem. The task can't finish his job and is running for 1 hour (until the pipeline is cancelled automatically). I have to make a downgrade to version 1.* of the task. Then the Build is running, but with this warning:

##[warning]Task 'Assembly-Info-Task' (1.1.39) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by markusmohr** [comment]
I removed this task and replaced it with my own powershell script.

**Comment by BMuuN** [comment]
Just pushed a new version (v2.1.92) which includes a flag under the "Logging" section to disable App Insights:

![image](https://user-images.githubusercontent.com/2933934/74041860-5b253380-49be-11ea-9582-491f53138e3f.png)

Can you let me know if this fixes your issue as I don't have an on-prem solution to recreate your issue therefore I haven't been able to fully test this fix.
