### ISSUE TITLE
Suggestion for improving documentation of NetFramework task

### ISSUE THREAD

**Issue by dmaassen** [BMuuN/vsts-assemblyinfo-task#129]
Hello,

It would be helpful to anyone wanting to write a yaml pipeline for a .NET Framework project if you included a yaml example for the **NetFramework** task.

My problem was I could not find documentation of the NetFramework task **name**: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-NetFramework@2

I was able to discover the name by creating a build pipeline using the classic editor, selecting the NetFramework task and then using the "View Yaml" menu option.

cheers

**Comment by BMuuN** [comment]
That's a great shout!

I had a YAML example for .Net Core but I was missing a .Net Framework example (I'm unsure how this was overlooked).  I've now update the [task parameters example](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Task-Parameters-Example) page to include an example for both tasks.
