### ISSUE TITLE
If the task is unable to communicate with application insights the assembly manifest data is not set

### ISSUE THREAD

**Issue by tomaustin700** [BMuuN/vsts-assemblyinfo-task#130]
Hi,
If telemetry is enabled but the task is unable to connect to application insights the assembly data is not set correctly. I encountered this as our firewall is doing ssl decryption and inspection and uses a self-signed cert, appliaction insights then throws the following error:
```
ApplicationInsights:CorrelationIdManager [ { Error: self signed certificate in certificate chain
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } ]
```
I'd expect the assembly data to still be set despite any application insight issues. To work around this I have had to disable telemetry.

**Comment by chwebdude** [comment]
Hi,
Same on Timeouts and stuff. Also it hangs around 5-7 minutes if no connection can be established. So builds are taking way longer as they should.

**Comment by BMuuN** [comment]
This is a known issue with App Insights and has previously been reported with issues #118 #119 #121 and #126.  A flag was added to the task to disable telemetry to overcome this issue.

Please let me know if setting the `Disable Telemetry` flag under the `Logging` category fix the issue for you...

**Comment by chwebdude** [comment]
Sorry, I just saw this issue and haven't checked the old ones...
I managed to disable the telemetry. Thank you. I think this should be an option in the task directly, or at least better documented. If I have time, I will do a PR :)
Otherwise it's a great extension! Thank you!

**Comment by tomaustin700** [comment]
@BMuuN Disabling telemetry does 'fix' the issue however I'd expect things to be more robust. Can't you communicate with insights after manifest data is set?

**Comment by BMuuN** [comment]
You and me both Tom.  Unfortunately this appears to be an underlying issue with App Insights and how it handles certificates, see these [certificate chain issues](https://github.com/Microsoft/ApplicationInsights-node.js/issues?q=is%3Aissue+certificate+chain) over on the App Insights GitHub page.

We need to load the app insights library as early as possible, as described [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs#sdk).  In the Assembly Info extension we call to track events without error and only when the task completes does App Insight attempt to ship it's telemetry data and this is where the issue arises and causes the task to hang.  This has only affected a small number of users and for this reason App Insights was left in the extension and a flag was added to allow users to disable the telemetry.

Hope this answers your question.
