### ISSUE TITLE
generateVersionNumbers creates wrong buildVersion (wildcard usage)

### ISSUE THREAD

**Issue by THues3010** [BMuuN/vsts-assemblyinfo-task#133]
The issue occurs during the second half of the day. The buildVersion is increased by one day, but the revision continues with the seconds from the next day.

In case you queue a new build on the second half of day 1 (any pm time) and in the first half of day 2 (any am time) the generated build version in combination with the revision is higher on day 1 build compared to day 2 build.

Example:
Day1: 2.0.7387.40030 (queued 10:14pm)
Day2: 2.0.7387.14447 (queued 08:01am)

**Comment by BMuuN** [comment]
Fixed with v2.2.103
