### ISSUE TITLE
Assembly version and assembly file version are ignored 

### ISSUE THREAD

**Issue by francoscarpa** [BMuuN/vsts-assemblyinfo-task#139]
In my pipeline, I use the **Assembly Info (.Net Framework)** and **Visual Studio build** tasks among the others. All works fine and the pipeline ends successfully, but the attributes setted on the Assembly Info (.Net Framework) task are not updated in the build artifacts. I have a very similar pipeline written in YAML and there the task does its job. Now I'm using a classic pipeline and I face this issue. In particular, I use version 2 of the task. Running the pipeline and inspecting the log of the Assembly Info (.Net Framework) task, I see this:

<img width="492" alt="Cattura" src="https://user-images.githubusercontent.com/9530051/80188716-dbe4ea80-8611-11ea-893e-f2ca8db80ec0.PNG">

which [should means that the task ends successfully](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Troubleshooting#build-output). **3.7.52.1** is the correct value I need, but when the pipeline ends and I check the `.exe` file of the application, I obtain this:

<img width="308" alt="Cattura1" src="https://user-images.githubusercontent.com/9530051/80189340-ce7c3000-8612-11ea-8e9f-207dadb465b3.PNG">

where 3.7.0.0 is still the value specified in the original `GeneralAssemblyInfo.cs` file.

**Comment by IanMercer** [comment]
Ended successfully but didn't find any matching files by the looks of it. You should see some log output from ` logger.info(`Processing: ${file}`);` showing that it found and processed your file.

Is the area under the red rectangle correct? Maybe try `**` globbing pattern instead?

**Comment by francoscarpa** [comment]
Actually, I was using a wrong path for the `GeneralAssemblyInfo.cs` file. I ignored the fact that the path of this file needed to be relative to the agent running the pipeline in which the source code is copied, not the repository itself (we're using TFVC). Previously, I was using a path like `$/.../...`, but again, that was relative to the repository, not the agent. Now, using `**/GeneralAssemblyInfo.cs` solves the problem.
