### ISSUE TITLE
csproj file not getting updated

### ISSUE THREAD

**Issue by fvilches17** [BMuuN/vsts-assemblyinfo-task#14]
Hello,

First of all, great extension. Such a time saver.

I did run into the issue where the details (e.g. Assembly Version, Copyright, Description, etc.) were not being written in the csproj file by the extension.

In my case I was deploying an Asp.NetCore (targeting .net core) web app.

**Steps to reproduce**

1. Create a simple Asp.Net Core MVC Web App (targeting .net core)

2. Add the following line to the _layout.cshtml file **
<footer>@PlatformServices.Default.Application.ApplicationVersion</footer>**

3. Create a simple build definition in VSTS, be sure to add the Assembly Info Task before build task of course.

4. In the Assembly Info Task, fill in the Assembly Version field with $(Build.BuildNumber). Build number format can be $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

5. Build and release the app (e.g. to Azure) via VSTS

6. Browse to any page of the web app using the _layout.cshtml file. 

**Excepted behaviour**
In the footer you should be able to see the build number.

**Actual behaviour**
Build number is the default 1.0.0.0

**Workaround**
Add the following to your project's csproj file

<PropertyGroup>
       <AssemblyVersion>1.1.0.0</AssemblyVersion>
</PropertyGroup>

**Explanation**
It seems that when the extension doesn't find a property in the csproj file, it skips writing it. Shouldn't the extension write this property even if it's not in the csproj file in the first place?

**Note**
I believe this is the case with all other properties (e.g. Copyright, File Version, etc.)

**Comment by BMuuN** [comment]
Hi fvilches17,

The workaround you've suggested is the correct implementation: - the extension will only replace existing attributes, it will not add attributes to csproj or assembly info files.  It has been built this way to prevent attributes being added to assemblies where they are not required.

In your case I would add the required element to your csproj file and populate it with a dummy value and allow the extension to replace the value at build time.

Hope this helps

**Comment by pbelousov** [comment]
Hi Bleddyn,

> It has been built this way to prevent attributes being added to assemblies where they are not required.

Agree that there is a risk to insert additional attribute to the wrong PropertyGroup. But as I see by default Visual Studio adds these attributes to the same PropertyGroup where "TargetFramework(s)" attribute is. So it's possible to check that if a user specified input for your task but the .csproj file doesn't have it in the same PropertyGroup as TargetFramework(s) then we could add it. 

Here it the example code:

```
#set informational version
if (![string]::IsNullOrWhiteSpace($InformationalVersion)) {
    
    if ($group.Version -eq $null -And ($group.TargetFramework -ne $null -Or $group.TargetFrameworks -ne $null)) {
        $newElement = $filecontent.CreateElement("Version")
        $group.AppendChild($newElement)
    }

    if ($group.Version -ne $null) {
        $group.Version = $InformationalVersion
        Write-Host "`tVersion: $InformationalVersion"
    }
}
```

One problem I see it's when a user changed .csproj file manually and one PropertyGroup with TargetFramework(s) attribute and another PropertyGroup with Version attribute.

What do you this on this?

Thank you in advance!

**Comment by BMuuN** [comment]
Evening All,

Thanks for the feedback!

A new task parameter has been added to `Insert Attributes` if the are not present in the source files.  This feature has been added to v1.1.36, see the marketplace [readme](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task) for further explanation.

I've also added new functionality for wildcard versioning, please see the [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning) for instructions on how to implement this feature.

Please do let me know if you run into any issues with the new version.

**Comment by DaveKLloyd** [comment]
I'm a little confused, Does the Insert Attribute flag add the missing attribute to the .csproj file? 
It doesn't seem to be working for me. I am using Version 2.* of the tool. 
BTW this would be a great feature if it works as .sqlproj's are the same as .net Core the Version attribute is not there in the file if set to 1.0.0.0.

**Comment by BMuuN** [comment]
Yes the `Insert Attributes` flag will add missing attributes to the file however the attribute is only added if a value is supplied from the task.

For `*.sqlproj` projects the assembly information data is set in the `AssemblyInfo.cs` file.  To populate data in a `*.cs` file ensure you've added the task `Assembly Info (.Net Framework)`.

**Comment by DaveKLloyd** [comment]
I got it working. My fault. Thank you
