### ISSUE TITLE
Setting AssemblyVersion in AssemblyInfo.cs doesn't update true build version

### ISSUE THREAD

**Issue by AdamDiament** [BMuuN/vsts-assemblyinfo-task#146]
Thanks for the great plugin. I am using the dotnetcore version to successfully set the AssemblyVersion field to major.minor.build - where major and minor were set by me manually in the AssemblyInfo.cs file before the push, and build was set from an azure pipeline variable $(Build.BuildId)

AssemblyInfoBefore: [assembly: AssemblyVersion("0.9")]

Presumed assembly info after: [assembly: AssemblyVersion("0.9.1139")] where 1139 is the build number from azure.

Output in the plugin console on azure dev ops: 

![image](https://user-images.githubusercontent.com/6513834/84488908-8d66da80-aca9-11ea-8ba2-b4a123cca2fa.png)

I am running the task before the build step on dev ops. However in my codebase I display the version to the user, and the build version comes out as zero, perhaps indicating the file was not updated after all?

This is the code I use to get the version to display to the user.
```

            var version = Assembly.GetExecutingAssembly().GetName().Version;

            return $"{version.Major}.{version.Minor}.{version.Build}";
```

And I see 0.9.0 instead of the expected 0.9.1139

Any help appreciated!

**Comment by akhubani** [comment]
Hi Adam,

In your return statement, have you tried using version.Revision instead of
version.Build?
Something like: return $"{version.Major}.{version.Minor}.
*{version.Revision}*";

Regards,
Amar Khubani

**Comment by AdamDiament** [comment]
> Hi Adam, In your return statement, have you tried using version.Revision instead of version.Build? Something like: return $"{version.Major}.{version.Minor}. *{version.Revision}*"; Regards, Amar Khubani


Thanks Amar, but no, because that relates to the fourth digit in x.x.x.x (major.minor.build.revision). I need the build number.

**Comment by BMuuN** [comment]
Hi @AdamDiament are you able to post a screenshot of the version numbers displayed from the `Properties - Details` tab for either the `*.dll` or `*.exe`?

**Comment by BMuuN** [comment]
Closing as received no response.  Feel free to re-open if you can provide the information requested.
