### ISSUE TITLE
AssemblyInfo.Cs gets updated but not committed into the repository

### ISSUE THREAD

**Issue by AshK14** [BMuuN/vsts-assemblyinfo-task#147]
Hi,

The plugin is working great but I would also like the updated AssembyInfo.Cs file to get committed into the TFVC repository.
Is there any way to do this?

Thanks for your help.

**Comment by IanMercer** [comment]
The best way to label builds with the built-version-number is the Azure Dev Ops task for this purpose, but that's for Git repos. Automated commits of actual source files back to a repository on every build are generally a bad idea as they pollute the commit log with a ton of noise, and if you have an automated build for every commit and incrementing build numbers, you could create an infinite loop. You also have the potential for conflicts.

**Comment by AshK14** [comment]
@IanMercer Can you please let me know what that Azure DevOps Task is called?
We use "TFVC - Check-in changes" task for TFVC repos. 

Now I want to do the same for Git Repo on Azure Devops

**Comment by IanMercer** [comment]
Sorry I meant 'feature' not 'task'. It's an option under under `Get Sources`

![image](https://user-images.githubusercontent.com/347540/87801455-95fc8480-c804-11ea-9a3c-5d129c064a97.png)

**Comment by BMuuN** [comment]
Closing.  As @IanMercer correctly stated: - committing the change back into the repo would cause an infinite build loop.  The best choice of action is to make use of the "Tag Sources" feature.
