### ISSUE TITLE
Getting the version number into a build variable

### ISSUE THREAD

**Issue by andyste1** [BMuuN/vsts-assemblyinfo-task#154]
In my build task, say I set the Assembly version to something like "1.2.*.0". The asterisk will be replaced by the number of days since 1/1/2000, or similar. In the build log for the AssemblyInfo task, I can see a line like this:-

Assembly version: 1.0.7612.1

Now, what I would like to do is label my source with this version number (after a successful build). I know you can label the source after a successful build via the "Get sources" build task, where there is a "Label format" textbox that allows the use of build variables. The big question is, is it possible to get the version number generated by your build task into a build variable, which I can subsequently use in the above textbox on the "Get sources" build task?

**Comment by BMuuN** [comment]
Interesting question...

The task does produce [output variables](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Output-Variables) however tagging a build with a version number is not something I've been able to get working with the "Tag Sources" options in Azure DevOps.

It should be possible to "Tag sources" as this is the final step in the build process but this is something that I've not been able to get working with the current version, the tag always ends up being `$(AssemblyInfo.Version)`:

![image](https://user-images.githubusercontent.com/2933934/98047638-2d253080-1e24-11eb-903b-dca74eb4e23a.png)

This issue maybe related to the output variables not being explicitly set in the task manifest, which is something I've addresses on a feature branch `AutoTests`, see the [OutputVariables](https://github.com/BMuuN/vsts-assemblyinfo-task/blob/AutoTests/src/netcore/task.json#L314) section defined for the Net Core task on this branch.  This section is not defined in the [current version](https://github.com/BMuuN/vsts-assemblyinfo-task/blob/master/src/netcore/task.json).

I'll create a test build for the `AutoTests` feature branch and have a play to see if this is an area we can resolve as it would also help my development process.

> On a separate note I've also tried settings the version number in the "Build number format" and not had any luck.  I'm convinced we cannot set the version number here as the build name is defined when a build is created and we do not have a version number at this point 😟

**Comment by andyste1** [comment]
I've done a bit of googling and found this article: https://stackoverflow.com/questions/50591488/vsts-label-sources-not-reading-build-phase-output-variable

I have tried the workaround/hack of updating the build number, and it seems to work for our needs. I actually append the assembly ver to the build number:

`Write-Host ("##vso[build.updatebuildnumber]$(build.buildnumber) v$(AssemblyInfo.Version)")`

which results in a build number (and TFS label) in the format "foobarapp_yyyymmdd.n v1.2.3.4". It seems to do the trick, and provides us with our missing link of being able to connect a version to a build (and a label/point of time in the source), which was almost impossible before.

**Comment by BMuuN** [comment]
Nice find!  I did not know about the `"##vso[build.updatebuildnumber]` command.  Interestignly there's also one to update the release name `##vso[release.updatereleasename]my-new-release-name` as documented here: [https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#release-commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#release-commands)

**Comment by TejinderEvry** [comment]
Hi @andyste1, @BMuuN 
Did try this `(Write-Host ("##vso[build.updatebuildnumber]$(build.buildnumber) v$(AssemblyInfo.Version)"))`  on my pipeline. 
![image](https://user-images.githubusercontent.com/42029297/107228826-1a358400-6a43-11eb-8ce0-64c30810d595.png)

However, getting error on AssemblyInfo.Version. It doesn't seem to be exist.
![image](https://user-images.githubusercontent.com/42029297/107228949-4224e780-6a43-11eb-8383-c0fb7e239b65.png)


Any suggestions ? 

PS: I am not much experienced in Azure :)

**Comment by BMuuN** [comment]
Closing this issue as the functionality to tag a build and update the name of a build has been added to v3
