### ISSUE TITLE
.Net framework task adding 'using' statement in cs file

### ISSUE THREAD

**Issue by vkbishnoi** [BMuuN/vsts-assemblyinfo-task#167]
Hi,

I am using this task to update AssemblyVersion and AssemblyFileversion in GlobalAssemblyinfo.cs file.

It is updating the versions correctly but along with that it is adding a using statement as well

using System.Runtime.CompilerServices;

Is there a switch to stop adding of using statements? Or it is a known behaviour?
We have a rule set for using statements to be added in certain order and because of this my build is failing.

-Vishal

**Comment by BMuuN** [comment]
Hey Vishal thanks for reaching out.  Unfortunately there's no switch to disable this behaviour.

One of the tasks main features is adding missing attributes if they do not exist and to ensure the application compiles both `System.Runtime.CompilerServices` and `System.Reflection` are added as using statements.

Looking at the code the task will always attempt to add these using statements if they are missing.  I've added a fix to ensure they're only added if the user is inserting missing attributes however that fix won't ship until the next version (`v3.0.x`).  For now, I can only suggest you add the using statements to your `GlobalAssemblyInfo.cs` in the correct order to prevent the task for adding it.

**Comment by vkbishnoi** [comment]
Thanks for your reply. I will wait for next version.

**Comment by BMuuN** [comment]
Closing this issue as version 3 has been released.
