### ISSUE TITLE
Informational version variables not resolved

### ISSUE THREAD

**Issue by roland-gyavol** [BMuuN/vsts-assemblyinfo-task#169]
Hi there,

First of all thank you for this tool, it really helps us in our project.

I'd like to ask a question, maybe I'm missing something obvious here: The variables in the informational version field are not parsed, meaning that the result is the variable as-is.

Steps to reproduce: 
1. Specify $(date:yyyy) in the Informational Version
2. Specify $(date:yyyy) in the Copyright field
3. Expected result: both fields get 2021
4. Actual result: Copyright gets 2021 but the Product version stays with $(date:yyyy)

Let me know if you need more details,
Thanks in advance,

Roland

**Comment by BMuuN** [comment]
Thanks for reaching out.  It looks like you're using date/time formats for v1 of the task.  If you're using v1 then unfortunately only the copyright field supports these date transforms.  Good news if you're using v2 then all fields support the date transforms.

Checkout the wiki article [here](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Date-&-Time-Format) for more examples as the format changed between v1 and v2.

**Comment by roland-gyavol** [comment]
Thank you very much for the quick response. It works just as expected. 

Cheers,
