### ISSUE TITLE
impossible to set $Build.DefinitionName as described in the wiki on dev.azure.com -> Pipelines

### ISSUE THREAD

**Issue by Henry-Jones** [BMuuN/vsts-assemblyinfo-task#173]
the wiki states:

"To use the build revision number $(Rev:r) in the version number we must utalise the Build number format on the General tab of the build definition."

I searched for this place for a while, but could not find something akin to the "General tab" or a "build definition". Trying to define the $Build.DefinitionName in the yaml file did not work either.

I ended up using something like: name: $(date:YYYY).$(date:MM).$(date:DD).$(Rev:r) to at least rename the builds to the wanted release number.

Surprisingly this can later be referenced as $Build.Buildnumber. Maybe the wiki could be updated to reflect this.

**Comment by BMuuN** [comment]
Hey thanks for the feedback.  I've updated the wiki 👍
