### ISSUE TITLE
Output variables are empty

### ISSUE THREAD

**Issue by fdesrosiers** [BMuuN/vsts-assemblyinfo-task#175]
Hi,
     I'm not sure if it's a configuration error or a bug but the output variable seems to be empty after the task.

`
  - task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-NetFramework@2
    displayName: 'Set Assembly Manifest Data'
    inputs:
      FileNames: |
       **\AssemblyInfo.cs
       **\GlobalInfo.cs
      WriteBOM: true
      VersionNumber: '1.\*.\*'
      FileVersionNumber: '1.\*.\*'
      InformationalVersion: '1.\*.\*'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
         echo $($AssemblyInfo.Version)
         echo $($AssemblyInfo.FileVersion)
         echo $($AssemblyInfo.InformationalVersion)
         echo $($AssemblyInfo.PackageVersion)
`

In this exemple, the 4 variables print nothing but the task change correctly the version number in the assemblyInfo.cs.

**Comment by BMuuN** [comment]
This is a known issue with v2.  I released v3 of the task this afternoon which fixes this issue.  Please upgrade to v3 as outlined in the steps on #185
