### ISSUE TITLE
Core3.1 Angular project - Assembly numbers not applying

### ISSUE THREAD

**Issue by gwill1010** [BMuuN/vsts-assemblyinfo-task#179]
I've tried a couple of things and I'm not able to apply version numbers to my assemblies.  I have no idea where to start.

**Comment by BMuuN** [comment]
Hey, have you tried the wiki:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki
It contains some yaml examples that maybe able to point you in the right direction.
If you still have no luck feel free to re-open this issue and post the output from the task and I'll try my best to help.
