### ISSUE TITLE
Azure DevOps shows warning for task owner - Node 6 will be deprecated soon

### ISSUE THREAD

**Issue by vyrotek** [BMuuN/vsts-assemblyinfo-task#185]
DevOps logs this warning when using the task.

[warning] This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Comment by buckleyGI** [comment]
We are getting the same warning

**Comment by sebappale** [comment]
Last commit / release was 1,5 years ago.
@BMuuN will you have time to look at this, or will you need a PR from someone?

I have never developed a task but we need this in our production pipelines, so I guess I will have to try to fix this if a fix ain't coming.

Does anyone know of a alternative to this task with similar features, as a last resort if this one stops working?

**Comment by BMuuN** [comment]
I'm currently looking at this issue.  Unfortunately following the upgrade path to Node10 break the extension.  I'm working to fix the issues so please bear with me.

**Comment by buckleyGI** [comment]
Ha! Was about to learn how to build a DevOps extension. Maybe I still do as a weekend project..

While thinking of creating a pull request, which would have taken me on a TS learning curve, I looked for instruction on how to build this extension. There is no documentation so is that straightforward?
The plan was to start with this [beginner tutorial of MS ](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)

Coffee coming you way :)
https://www.buymeacoffee.com/bleddynrichards

**Comment by BMuuN** [comment]
Thanks @buckleyGI appreciate it 👍🏼 

There are steps in the [Wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Debugging) to run and debug the extension locally.

I should also point out the active branch for this extension is `3.0.x`.  It's a version I've been trying to ship for some time but somehow the priority of this project always seems to get demoted down my list.  This branch also contains scripts in the `package.json` for building, running and testing the extension.

**Comment by BMuuN** [comment]
I've released a new version of the extension which addresses the Node10 warning mentioned in this thread and also introduces some new features.  This is a major version (v3.0.753) therefore you'll need to make a change in your pipelines to use "Task version 3.*".

You'll notice with this release there's a new logo - don't be alarmed it's still the same extension and you can find the code branch for v3 [here](https://github.com/BMuuN/vsts-assemblyinfo-task/tree/3.0.x).

Before you head off to update the task can I recommend you take this approach:

1) In your build pipeline clone the Assembly Info task, then on the new/copy set the task version to 3.*
2) Disable the existing task (version 2).

This approach ensures if there are any breaking changes introduced with v3 you can switch back to using v2.  I've read there are some issues with Node10 and on-premises setups so I highly recommend this approach to minimize any disruption to your workflow.

If you could respond to this issue and let me know it's the extension is working in your build pipelines I'd be very grateful.

**Comment by doormalena** [comment]
Just upgraded the task in our Azure DevOps yaml pipeline. Looking good so far. Node 6 deprecation warning is gone.

**Comment by buckleyGI** [comment]
Hi Bleddyn, The task works great here. No more warnings! Thank you

**Comment by vyrotek** [comment]
Looks good now. Thank you!

**Comment by sebappale** [comment]
I have a problem where it now crashes in a project with no matches for files to process. Is there a override flag to allow no files beeing processed?
We use shared build templates, so that is why I have the task in the pipeline even tho the project doesn't have any assmbly-info-files..

Error:
```
Setting .Net Framework assembly info...
##[error]No files found for: **\AssemblyInfo.cs, **\AssemblyInfo.vb
```

Before upgrade to 3.x:
```
Setting .Net Framework assembly info...
Finishing: Set Version for all assemblies
```

This used to work with 2.x, it just ignored it and continued.

I can't see anything that could solve this problem here?
https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Task-Parameters-&-Build-Yaml
