### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by TrevorFourie** [BMuuN/vsts-assemblyinfo-task#186]
Thank you firstly for a great tool.

I've tried everything and maybe I'm missing something.

I keep getting this warning
Detected file encoding: iso-8859-2
##[warning]Detected file encoding (iso-8859-2) is different to the one specified (utf-8).
GeneratePackageOnBuild --> false

I've tried setting the file encoding to auto and enable "Write unicode BOM" .. same with utf-8. Tried without enabling it. 

This is happening on the .Net Core Assembly Task pointing to .csproj

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>hidden</RootNamespace>
    <Company>hidden</Company>
    <Authors>hidden</Authors>
    <Product>hidden</Product>
    <PackageId>hidden</PackageId>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright © 2020</Copyright>
    <PackageReleaseNotes>Release</PackageReleaseNotes>
    <LangVersion>8</LangVersion>
    <AssemblyName>hidden</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <None Update="config\appsettings.jsontemplate">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.0" />
  </ItemGroup>
</Project>`

It still updates the file but the copyright symbol keeps changing to a ? 

Any recommendations I'm missing?

**Comment by BMuuN** [comment]
Hey @TrevorFourie can you set the `File encoding` to `utf-8` and ensure the checkbox for `Write Unicode BOM` is ticked.

Let me know how you get on.  If that still doesn't fix your issues can you re-open this issue and add the output from the task.

**Comment by TrevorFourie** [comment]
Hi,

I've tested it but still the same
##[warning]Detected file encoding (iso-8859-2) is different to the one specified (utf-8).

![image](https://user-images.githubusercontent.com/45752559/145766001-561004db-dc82-4279-87af-00e70c682972.png)

**Comment by BMuuN** [comment]
With those encoding settings is the copyright symbol displaying as a `?` or is it displaying the correct symbol ©

**Comment by TrevorFourie** [comment]
My apologies .. I never looked there .. but it is showing the copyright symbol now.

Thank you again for a great tool and the assistance!

**Comment by BMuuN** [comment]
Hey no worries at all just glad it's all working for you!
