### ISSUE TITLE
The YAML task definition should be either in the master readme or the overview

### ISSUE THREAD

**Issue by pijemcolu** [BMuuN/vsts-assemblyinfo-task#188]
IMO the YAML task definition [from here](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Task-Parameters-&-Build-Yaml#yaml) shouldn't be buried 3 links deep, but instead be available immediately in the master readme file.

**Comment by BMuuN** [comment]
Great shout.  I've added an example .Net Core yaml to the "Overview" page 👍🏼
