### ISSUE TITLE
NODE 6 Version Alert

### ISSUE THREAD

**Issue by ramonduraes** [BMuuN/vsts-assemblyinfo-task#191]
This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration

**Comment by BMuuN** [comment]
Thanks for letting me know @ramonduraes .  The task has been upgraded to Node10 with v3.0.755.  Please see issue #185
