### ISSUE TITLE
Node 6 execution handler is deprecated, update Task to Node 10 handler

### ISSUE THREAD

**Issue by pmize3** [BMuuN/vsts-assemblyinfo-task#192]
Today I got this warning logged when running this task.

![image](https://user-images.githubusercontent.com/1649167/143943769-7c970a75-39bf-4c4f-bcae-16d9f297331f.png)

Node 6 execution handler will be removed March 31st 2022. The task shoudl be migrated to Node 10.
Here's the article to upgrade tasks to Node 10.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md

**Comment by BMuuN** [comment]
Thanks for reaching out @pmize3.  This issue has already been addressed with issue #185

**Comment by pmize3** [comment]
Sorry I didn't see that one. Thanks for being on top of it and fixing it so quickly! 👍
