### ISSUE TITLE
This task uses Node 6 execution handler, which will be removed March 31st 2022

### ISSUE THREAD

**Issue by VAnzala** [BMuuN/vsts-assemblyinfo-task#193]
DevOps is giving me this warning:
`##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

Is there a change that needs to be made to the package.json?

**Comment by BMuuN** [comment]
Hey @VAnzala thanks for reaching out.  This issue has been fixed.  Please see issue #185
