### ISSUE TITLE
The task does not carry an implementation that is compatible with your current operating system 'Windows'

### ISSUE THREAD

**Issue by naji-makhoul** [BMuuN/vsts-assemblyinfo-task#209]
I'm trying to run task (Assembly Info (.Net Core & .Net Standard)
) but get error : 
`"A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'. Contact the task author for more details."`

 I have windows server 2019 server 64bit with hosted tfs 2018

**Comment by naji-makhoul** [comment]
it's working now after update the agent to latest version 2.200.2

**Comment by BMuuN** [comment]
That's awesome news.  Thanks for checking back and letting us know.  Appreciate it 👍
