### ISSUE TITLE
Corrupting .NET Framework projects

### ISSUE THREAD

**Issue by alexgurman** [BMuuN/vsts-assemblyinfo-task#212]
Version 2.3.105 of Assembly Info (.Net Core & .Net Standard) task just skipped .NET Framework projects present in the solution. Version 3.1.2 corrupts them, so that msbuild task throws error "The BaseOutputPath/OutputPath property is not set for project" for each .NET Framework project. I am attaching two log files from Versions 2.3.105 and 3.1.2 of Assembly Info (.Net Core & .Net Standard) on the same solution as well as msbuild task log files of the same solution.
[3.1.2 - Build.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811302/3.1.2.-.Build.log)
[2.3.105 - AssemblyInfo.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811304/2.3.105.-.AssemblyInfo.log)
[2.3.105 - Build.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811305/2.3.105.-.Build.log)
[3.1.2 - AssemblyInfo.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811306/3.1.2.-.AssemblyInfo.log)

**Comment by BMuuN** [comment]
You are correct v2 did detect .Net Framework project files and ignore them however the way it did this wasn't correct and it should never have been added.  It also prevented users from being able to use the task to target shared build.prop files and as a result the offending code was removed in v3.

If your application includes a mixture of .Net Framework and .Net Core/Standard projects the correct approach would be to alter the tasks "Source files" from looking for all project files `**/*.csproj` and instead target the correct projects for the task `**/SharedLib.csproj, **/Application.csproj, **/Domain.csproj` etc.

Hope this helps.

**Comment by alexgurman** [comment]
We have many micro services and use the same ADO template for them.
Approach of specifying .NET Standard projects explicitly by passing the
list as parameter will add to our maintenance efforts. Any way to bring
back the functionality via optional flag, false by default? So users can
"buy in" setting the flag to true and get the desired effect?

Thanks,
Alex.

**Comment by MellyDawgKY** [comment]
> Version 2.3.105 of Assembly Info (.Net Core & .Net Standard) task just skipped .NET Framework projects present in the solution. Version 3.1.2 corrupts them, so that msbuild task throws error "The BaseOutputPath/OutputPath property is not set for project" for each .NET Framework project. I am attaching two log files from Versions 2.3.105 and 3.1.2 of Assembly Info (.Net Core & .Net Standard) on the same solution as well as msbuild task log files of the same solution. [3.1.2 - Build.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811302/3.1.2.-.Build.log) [2.3.105 - AssemblyInfo.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811304/2.3.105.-.AssemblyInfo.log) [2.3.105 - Build.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811305/2.3.105.-.Build.log) [3.1.2 - AssemblyInfo.log](https://github.com/BMuuN/vsts-assemblyinfo-task/files/7811306/3.1.2.-.AssemblyInfo.log)

I second this one,  the error goes beyond that for me.  I was working with .net 4.6.2 console app.  error came up when trying to use assembly.vs, said to use csproj, then it.  I was able to inject the outputpath again to get beyond, yet the msbuild and vsbuild still blew up when trying to write the output, seriously kra.

**Comment by BMuuN** [comment]
To give some background on this issue: - v2 looked for the `Sdk` attribute on the `<Project>` element and if this attribute was found to contain either `Microsoft.NET.Sdk` or `MSBuild.Sdk.Extras` it was considered to be a .Net Core/Standard project e.g. `<Project Sdk="Microsoft.NET.Sdk">`.  This check was not correct as some .Net Core projects do not contain the `Sdk` attribute therefore this checked prevented the task from processing valid .Net Core/Standard project.  As a result the check was removed in v3.

As mentioned in a previous post (above) the correct approach would be to alter the tasks "Source files" from looking for all project files `**/*.csproj` and instead target the correct projects for the task `**/SharedLib.csproj`, `**/Application.csproj`, `**/Domain.csproj` etc.

A possible alternative is for the task to check for the presence of the `<TargetFrameworkVersion>` element which I believe to only be present in .Net Framework solutions.  Respectively .Net Core/Standard now use the elements `<TargetFramework>` and `<TargetFrameworks>` however I will have to do further research to verify this is a correct approach.  If you have any other thoughts on how to check if a project file is targeting .Net Core vs .Net Framework I'm all ears...

**Comment by BMuuN** [comment]
I've added a new flag to the .Net Core task which allows you to "Ignore/Skip .Net Framework Projects".  As mentioned above this looks for the `TargetFrameworkVersion` element.  

Please let me know how you get on with this fix.  I'll close this issue but please re-open if this is not working for your particular scenarios.
