### ISSUE TITLE
Wrong file encoding detected

### ISSUE THREAD

**Issue by chasewallis** [BMuuN/vsts-assemblyinfo-task#213]
The file with contents
```
<Project Sdk="Microsoft.NET.Sdk.Web">

</Project>
```
and most definitely having the BOM ﻿'EF BB BF' at the beginning is detected as an iso-8859-2, which in turn caused the below error.

```
Processing: D:\a\1\s\abc.xyz.Domain\abc.xyz.Domain.csproj
Detected file encoding: iso-8859-2
##[error]Error reading file: Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: ď
```

There were 7 other csproj files processed before this, each identified as utf-8, iso-8859-1, and iso-8859-2. All processed correctly, I verified the ones identified as utf-8 all had the BOM. for some reason the given file was not identified as BOM.

**Comment by BMuuN** [comment]
Have you tried setting the file encoding to `utf-8` rather than `auto`?

**Comment by BMuuN** [comment]
If the file encoding is still causing you issues you may want to open the `*.csproj` files with VSCode and observer the file encoding in the toolbar:

![image](https://user-images.githubusercontent.com/2933934/156440700-8cecc18a-7671-4a8a-8419-bcb588848ac0.png)

Clicking the encoding allows you to re-open or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/2933934/156440769-6216a4c5-7146-40de-b3a7-2bcaca720b81.png)

Clicking save will prompt which encoding you wish to use:

![image](https://user-images.githubusercontent.com/2933934/156440968-fedcf211-8c90-49f4-9b87-28971dd98fa3.png)

Hope this helps as this is how I've resolved most file encoding issues with my own `*.csproj` files.

**Comment by BMuuN** [comment]
Closing due to no response. Please re-open the issue if you are still facing issues.
