### ISSUE TITLE
GenerateDocumentationFile is all-or-nothing

### ISSUE THREAD

**Issue by turbodrubin** [BMuuN/vsts-assemblyinfo-task#214]
I note that in #199 support for the `<GenerateDocumentationFile/>` element was added, but by virtue of being a boolean, it's become an all-or-nothing setting across _all_ projects that are considered (_i.e._ by the `FileNames` setting).

In my circumstance, I have _one_ project among many in a solution that I want documentation generated for, and I enabled that by putting a `<GenerateDocumentationFile>true</GenerateDocumentationFile>` element in that specific `.csproj`.

`@2` of the task "left it alone", and my results were as I wished. When I upgraded to `@3` of the task, creation of the XML documentation file is disabled by the assembly-attribute setting.

Could the default be a neutral "neither true-nor-false" that doesn't set the assembly attribute either way? Explicitly setting `true|false` could then apply that explicit setting to the considered projects.

**Comment by BMuuN** [comment]
This issue has been raised once before so I think the best solution is to convert all Boolean values to use a drop down list of `ignore|true|false` and only populate the project file if `true|false` are selected.  

Leave it with me and I'll get this change implemented 👍

**Comment by dlbromen** [comment]
For what it's worth, this is also a breaking change for solutions/projects that omitted the `GenerateDocumentationFile` property entirely, but were still getting the documentation to generate by setting the `DocumentationFile` property.

> If you specify this property but you set GenerateDocumentationFile to false, the compiler does not generate a documentation file. If you specify this property and omit the GenerateDocumentationFile property, the compiler does generate a documentation file.

https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#documentationfile

So the new behavior with no changes to the projects and simply an ADOS Task upgrade to 3.1.2 results in no documentation being generated.

**Comment by BMuuN** [comment]
This has been addressed in the latest version v3.1.6
