### ISSUE TITLE
Support wildcards in the Source Files text area

### ISSUE THREAD

**Issue by jrummell** [BMuuN/vsts-assemblyinfo-task#22]
It would be great if you could specify a minimatch pattern like `**/*.csproj` instead of individual files for netstandard or core projects.

**Comment by berhir** [comment]
I use just `*.csproj` to update all project files recursively in the specified source folder.

**Comment by BMuuN** [comment]
Your request has been implemented in v2.0.65. Apologies for the delay implementing this change!

Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
