### ISSUE TITLE
Output variables for .net framework not working

### ISSUE THREAD

**Issue by dannoe** [BMuuN/vsts-assemblyinfo-task#225]
Because the variables are not set as "isOutput".

**Comment by BMuuN** [comment]
This was a know bug that was fixed in `v3`.  Can you confirm what version of the task you are using?

**Comment by dannoe** [comment]
I am using the v3 version. It is fixed in the core version but not in the Framework version.

But it has no priority for me now, as the output variables do not work with using # (reusing Version parts)

**Comment by BMuuN** [comment]
I see the issue!  Thanks for reporting this I'll get a fix out a.s.a.p.

**Comment by BMuuN** [comment]
Fixed in v3.2.0
