### ISSUE TITLE
No file found with filename: AssemblyInfo.vb

### ISSUE THREAD

**Issue by Yawarmurtaza** [BMuuN/vsts-assemblyinfo-task#23]
It works for C# projects / solutions but not for VB.Net.
I have the following configurations:

**Source Folder** = $/root/apps/"applicationName"/"applicationName".sln
**Source Files** = AssemblyInfo.vb

and when this task is run i get a warning message " ##[warning]No file found with filename: AssemblyInfo.vb" 

Tasks completed successfully but it doesn't do anything because it cant find AssemblyInfo.vb. 

Could anyone please help me fix this?

Thanks in advance.
Yawar

**Comment by BMuuN** [comment]
Set the **Source Folder** to $(Build.SourcesDirectory).  The extension will recursively search the source folder for any files specified in the source files section.

**Comment by BMuuN** [comment]
@Yawarmurtaza did the above suggestion solve your issue?

**Comment by Yawarmurtaza** [comment]
@BMuuN - Im really sorry for not getting back to you on this. Yes your suggestion worked.
Regards
Yawar
