### ISSUE TITLE
Net core csproj Informational Version setting Version property instead of InformationalVersion

### ISSUE THREAD

**Issue by inoreip** [BMuuN/vsts-assemblyinfo-task#24]
For netcore projects (tested with core 2) the version element is set to the Informational Version property from the task. This is incorrect as the Version element must conform to the **d.d.d.d** format where as the Informational Version property is free text.

It looks like this line is incorrect from the task:

```javascript
$group.Version = $InformationalVersion
```

The csproj file has the following elements in regards to versioning.

```xml
<PropertyGroup>
    <AssemblyVersion></AssemblyVersion>
    <FileVersion></FileVersion>
    <InformationalVersion></InformationalVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>
```

I am unsure what should be setting the Version element, however this is displayed as the product version in Windows when viewing the details of the dll from disk.

# EDIT
I should note that in my case I am using the `$(Build.BuildNumber)` to populate the Information Version property which is in the format `$(Build.DefinitionName)_$(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)`. This of course is not a valid version string and therefore will not build.

Very useful task great work.

Thank you

**Comment by BMuuN** [comment]
The `Version` element is the correct element for the `Informational Version`.  If you specify a `Package version` from Visual Studio project properties it will populate the `Version` element.  Specifying a `Assembly version` will populate the `AssemblyVersion` element and; specifying a `Assembly file version` will populate the `FileVersion` element.
