### ISSUE TITLE
Wildcard version numbers

### ISSUE THREAD

**Issue by andyste1** [BMuuN/vsts-assemblyinfo-task#25]
Hi, I can't figure out how to use a wildcard version number, e.g. `1.0.*`. When I use this value in the Assembly Version parameter, the task's build output displays "AssemblyVersion: 1.0." and the subsequent build task fails ("Error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]]").

What am I doing wrong, or doesn't your task support wildcards? Any chance this could be added?

**Comment by BMuuN** [comment]
Hi @andyste1 you're doing anything wrong mate.  Unfortunately the task doesn't support wildcard version numbers and support for it won't be added as I'm not sure it's currently possible from VSTS.

You can either specify a static version number from the task or as documented in the [Overview](https://github.com/BMuuN/vsts-assemblyinfo-task/blob/master/src/Overview.md#version-number) you can configure the **Build number format** for your desired version number.

For clarification: - the idea behind this task was to ensure all projected compiled within a build shared the same version number which allowed us to trace the code on our servers back to a specific build to see the commits associated with that release.

Hope this helps.

**Comment by andyste1** [comment]
No problem. Unfortunately the build number format didn't suit us as we like to manually increment the major & minor numbers but generate the build and release numbers automatically.
I've now written a powershell build task to generate these numbers (using the same algorithm as msbuild when it encounters a wildcard version of say "1.0.*"), assign these to variables and use them in your build task's version parameters, e.g. "1.0.$(ver_build).$(ver_release)".

**Comment by tarunaroraonline** [comment]
@andyste1 can u share your powershell task here?

**Comment by andyste1** [comment]
@tarunaroraonline here it is:

    $d1 = '2000-01-01'
    $d2 = $(Get-Date)
    $ts = New-TimeSpan -Start $d1 -End $d2
    $ver_build = $ts.Days
    
    $midnight = $(Get-Date -Hour 0 -Minute 00 -Second 00)
    $ts = New-TimeSpan -Start $midnight -End $d2
    $ver_release = [math]::Round($ts.TotalSeconds / 2)
    
    Write-Host "##vso[task.setvariable variable=ver_build]$ver_build"
    Write-Host "##vso[task.setvariable variable=ver_release]$ver_release"
    Write-Host "ver_build: $ver_build"
    Write-Host "ver_release: $ver_release"    

You'll need to add "ver_build" and "ver_release" to the build definition's Variables tab. In the "Assembly Info" task I set the file version and assembly version to:

> 2.1.$(ver_build).$(ver_release)

(We set major & minor by hand, e.g. when we branch for release). 

The PS script generates the build and release numbers as no. days since 1/1/2000, and no. seconds since midnight divided by 2.

**Comment by BMuuN** [comment]
Nice work @andyste1!
Do you mind if I add this to the task?

**Comment by BMuuN** [comment]
@andyste1,

Thanks for the feedback and the code snippet!

I've added the functionality for wildcard versioning to v1.1.36, please see the [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning) for instructions on how to implement this feature.

I've credited you on the [release notes](https://github.com/BMuuN/vsts-assemblyinfo-task/blob/master/ReleaseNotes.md).

Please do let me know if you run into any issues with the new version.
