### ISSUE TITLE
v3 doesn't seem to create the "AssemblyInfo.Version" output variable

### ISSUE THREAD

**Issue by andyste1** [BMuuN/vsts-assemblyinfo-task#260]
I've been using your v2 task for a while without any issues. Today I created a build pipeline for a new .Net Core solution, and added the "assembly info" task, which I noticed defaulted to v3 (and the new orange icon). When I ran the build, a subsequent Powershell task (that uses the "AssemblyInfo.Version" variable) failed:

AssemblyInfo.Version : The term 'AssemblyInfo.Version' is not recognized as the name of a cmdlet, function, script file, or operable rogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Temp\VSTS Agent\_work\_temp\af68b752-2ec8-4e1e-b013-0dea18f47eb3.ps1:4 
char:77
v$(Asse ...
+                                                                             
~~~~
    + CategoryInfo          : ObjectNotFound: (AssemblyInfo.Version:String) [] 
   , ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

It works when I change the assembly info build task version to v2.

Out of interest what's different with the v3 task other than some new attributes? I'm setting up a build for a .Net6 solution, so will the v2 task still be okay to use here?

**Comment by BMuuN** [comment]
Hey @andyste1 to use output variables in v3 you are required to give the output variables a reference.  Please see the "Output Variables" group box of the task.  If, for example, you specify a reference name of "AI" you can then reference the output variables as follows:

```powershell
Write-Host "Version: $(AI.AssemblyInfo.Version)"
Write-Host "File Version: $(AI.AssemblyInfo.FileVersion)"
Write-Host "Informational Version: $(AI.AssemblyInfo.InformationalVersion)"
```

Hope this helps.

**Comment by andyste1** [comment]
Great, I see it now. Thanks for clarifying!
