### ISSUE TITLE
Output variables with Keep Parts of Original Version

### ISSUE THREAD

**Issue by OmiCron07** [BMuuN/vsts-assemblyinfo-task#266]
I'm using the Keep Parts of Original Version functionality, but the output variables are not the final value: /property:ApplicationVersion="#.#.#.1349". I'm using the .Net framework version.

Can we get the final version like "1.2.3.1349"?

> ##[section]Starting: Set Assembly Manifest Data
> ==============================================================================
> Task         : Assembly Info (.Net Framework)
> Description  : Set assembly information such as Version, Copyright and Trademark etc.
> Version      : 3.2.0
> Author       : Bleddyn Richards
> Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
> ==============================================================================
> ##[group]Task Parameters...
> Source folder: C:\_Agents\Agent01\_work\8\s
> Source files: **\SharedAssemblyInfo.cs
> Insert attributes: false
> File encoding: auto
> Write unicode BOM: false
> Title: 
> Product: 
> Description: 
> Company: 
> Copyright: 
> Trademark: 
> Culture: 
> Configuration: Test
> Assembly version: #.#.#.1349
> Assembly file version: #.#.#.1349
> Informational version: #.#.#.1349
> Log Level: verbose
> Fail on Warning: false
> Build Tag: 
> Build Number: 
> ##[endgroup]
> 
> Setting .Net Framework assembly info...
> ##[group]Processing: C:\_Agents\Agent01\_work\8\s\AbfSources\Nms\Products\ABF\Sources\SharedAssemblyInfo.cs
> Detected file encoding: utf-8
> AssemblyVersion --> #.#.#.1349
> AssemblyFileVersion --> #.#.#.1349
> AssemblyInformationalVersion --> #.#.#.1349
> AssemblyConfiguration --> Test
> Verify file encoding: iso-8859-1
> ##[endgroup]
> 
> Setting output variables...
> Tagging build...
> ##[section]Finishing: Set Assembly Manifest Data

**Comment by OmiCron07** [comment]
After some tests, I think that the placeholder (#) is never replaced.

**Comment by OmiCron07** [comment]
The placeholders are replaced when I check the file version of the compiled files but does not seem to be in the parameters of the msbuild compilation:

![image](https://user-images.githubusercontent.com/31325575/182387855-cefb1571-d015-4370-a99e-2abbc0130c47.png)

**Comment by OmiCron07** [comment]
Further tests, I added a PowerShell script to output the variables:

```
[string[]]$versionNumbers = "$(AI.AssemblyInfo.FileVersion)".Split('.',[System.StringSplitOptions]::RemoveEmptyEntries)

Write-Host "Major: $($versionNumbers[0])"
Write-Host "Minor: $($versionNumbers[1])"
Write-Host "Patch: $($versionNumbers[2])"
Write-Host "Revision: $($versionNumbers[3])"
```

> ##[section]Starting: PowerShell Script copy
> ==============================================================================
> Task         : PowerShell
> Description  : Run a PowerShell script on Linux, macOS, or Windows
> Version      : 2.151.1
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
> ==============================================================================
> Generating script.
> ========================== Starting Command Output ===========================
> ##[command]"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\_Agents\Agent01\_work\_temp\5b11d3d8-2b1f-465d-bd80-94c0b0acc3d0.ps1'"
> Major: #
> Minor: #
> Patch: #
> Revision: 1357
> ##[section]Finishing: PowerShell Script copy
>

**Comment by paxsentry** [comment]
I've got the same issue, I believe it is coming somewhere from the Utils.setVersionNumber() function, but not sure.

**Comment by OmiCron07** [comment]
So, the task is totally broken?

**Comment by BMuuN** [comment]
I shall take a look at this issue over the weekend for you.
