### ISSUE TITLE
How to fully integrate into pipeline with push command

### ISSUE THREAD

**Issue by nitewulf** [BMuuN/vsts-assemblyinfo-task#268]
I'm sure that I'm just not setting something correctly in my yaml.  I used to do the standard restore, build, pack, and push sequence and am trying to replace build this this awesome extension to get meta data generated.  I replaced build and pack with this extensions command and now my pipeline looks like this:

`
#Restore packages
  - task: DotNetCoreCLI@2
    displayName: 'Restore package dependencies'
    inputs:
      command: 'restore'
      projects: '${{ parameters.solution }}'
      configuration: '${{ parameters.buildConfiguration }}'
      feedRestore: '${{ parameters.feed }}'
      includeNuGetOrg: true

  # Build and set metadata
  - task: Assembly-Info-NetCore@3
    displayName: 'Build and set metadata'
    inputs:
      Path: '$(Build.SourcesDirectory)'
      FileNames: |
        **/*.csproj
        !**/*[tT]ests.csproj
        !**/*[tT]est.csproj
      InsertAttributes: true
      FileEncoding: 'auto'
      WriteBOM: false
      GeneratePackageOnBuild: 'true'
      LogLevel: 'verbose'
      FailOnWarning: false
      DisableTelemetry: false
      VersionNumber: '$(calculatedVersion)'
      FileVersionNumber: '$(calculatedVersion)'
      InformationalVersion: '$(calculatedVersion)'
      Copyright: 'Copyright © $(date:YYYY)'

  # Publish assemblies
  - task: DotNetCoreCLI@2
    displayName: 'Publishing the artifact to feed'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '${{ parameters.feed }}'
`
When push runs it fails and I get this message:

##[error]No packages matched the search pattern.

Is there a way to add more logging to the Assembly-Info-NetCore@3 task so I can see where the packages get created maybe?  For example with the .NetCoreCli task running pack shows output like this:
Successfully created package '/home/vsts/work/1/a/{project}.nupkg'.  It would be helpful to see output like that to verify the package gets created.

Or is there something super obvious that I'm doing wrong?  Appreciate any help.  

Also sorry about the formatting.  I also don't know how to tell the editor to leave the yaml alone and not treat it as mark down.

**Comment by BMuuN** [comment]
Hey @nitewulf you'll still need the `dotnet build` task in your pipeline!  The Assembly Info task will only set the metadata in the `*.csproj` files - it does not compile your projects.  Also, please ensure the Assembly Info task comes before the `dotnet build` task or else your meta data won't get compiled into your assemblies.  For further info on this process please see the [Market Listing](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task) page.

**Comment by nitewulf** [comment]
That makes a ton of sense.  I knew I was doing something obviously wrong.  Mostly not reading the documentation, "How to use the build task" - I see it now, plain as day.  Sorry and thanks.

**Comment by BMuuN** [comment]
No worries at all.  Glad to help 👍
