### ISSUE TITLE
Add an option to break the build on warnings

### ISSUE THREAD

**Issue by Gimly** [BMuuN/vsts-assemblyinfo-task#27]
It would be great if there was an option to break the build as soon as there is a warning.

For example, I got a warning that it didn't update the assembly info, and it kept the default, which created a release with an incorrect version number. I would have preferred the build to fail, given that the error was because the csproj name had changed and I hadn't updated my build definition.

**Comment by BMuuN** [comment]
Option added to v2.1.91
