### ISSUE TITLE
CSProj File without PropertyGroup fails

### ISSUE THREAD

**Issue by Chaosflo** [BMuuN/vsts-assemblyinfo-task#288]
In my project we use the Assembly Write Task.

So I found a bug after using Directory.Build.props!

If you don't have atleast one `<PropertyGroup></PropertyGroup>` in the csproj File the build fails with this error `##[error]Error reading file: null
`

There is a workaround by adding atleast one `<PropertyGroup></PropertyGroup>` this can be an empty one too! =)

**Comment by Chaosflo** [comment]
https://github.com/BMuuN/vsts-assemblyinfo-task/blob/6792835d9fed4106cc4b01c85f36952daceac8a2/src/netcore/index.ts#L231-L234

These are the line which fails

**Comment by Derpalus** [comment]
This issue seems to be the same thing, just worded differently: https://github.com/BMuuN/vsts-assemblyinfo-task/issues/283

**Comment by Chaosflo** [comment]
Yep seems like it! Thanks

**Comment by BMuuN** [comment]
The code mentioned above will error if no `<Project>` element is found.  If no `<PropertyGroup>` element is found the task will create one.

Can you confirm if you are running the latest version `v3.2.2` and if you are targeting either the `.csproj` or `Directory.Build.props` files?

**Comment by Chaosflo** [comment]
Hey! 
I had time to check this up, its a looong story till now.
What I needed to realize was the pinning of version of this task
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#task-versions

So I were never been able to test out the new version, which gave me headaches =) 

But after that I could finally test it, and what should I say? 
Works fine till now! 
So for me this issue is closed now

Thanks for patience
