### ISSUE TITLE
Error : The BaseOutputPath/OutputPath property is not set for project

### ISSUE THREAD

**Issue by Derpalus** [BMuuN/vsts-assemblyinfo-task#297]
Notice that this error is not from the assembly info task, this error is reported when I try to build a my project after this task has run on it. The assembly info task runs without any errors, but corrupts the csproj file.

The reason for this error is that this task puts `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` at the top of the file. This breaks my build as apparently this line has to be added AFTER any build configurations.

See answer from Philip Atz in this SO question: https://stackoverflow.com/questions/9086795/the-outputpath-property-is-not-set-for-this-project

**Comment by BMuuN** [comment]
The task does not add `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` so I'm unsure where this is coming from?  The only elements the task will add is the `<PropertyGroup>` (if an existing element cannot be found) and,  if `InsertAttributes` is set to `true` the task will add the assembly info elements themselves.

I'm going to close this issue as I'm confident the task is not causing your issue but I am curious as to what is adding the `CSharp.targets` to your project file - keep me updated!
