### ISSUE TITLE
Date in FileVersion

### ISSUE THREAD

**Issue by TPGEric** [BMuuN/vsts-assemblyinfo-task#32]
Hi,
I just want to put a number like $(Year:yy)$(DayOfYear) in my FileVersion Attribute.
How do you do this ?

Even if I try a format like this $(Version.Major).$(Version.Minor).$(date:yymm) 
File version is like this : "File Version: 2.0."

Any Idea ?

**Comment by BMuuN** [comment]
Hi @TPGEric 

Date transformations are only supported in the `Copyright Attribute` field, therefore `$(date:yymm)` won't work within the versions fields.

For an explanation on what values are supported in the version fields please see the following [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning) article on versioning.

For an explanation on what values are supported in the copyright fields please see the following [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Copyright) article.

Hope this helps.

**Comment by TPGEric** [comment]
Hi BMuun, 

Thanks for your response.
To achieve my task, I finnaly used a powerShell script with a build variable :
`
$versionFile = '{0}{1}' -f  (Get-Date -UFormat "%y"), (Get-Date).DayOfYear
Write-Host "##vso[task.setvariable variable=Version.FileDate]$versionFile"
`

and use it in File Version Attribute :
`$(Version.Major).$(Version.Minor).$(Version.FileDate).$(Build.BuildID)`

If it can help someone else.
