### ISSUE TITLE
Assembly-Info-NetCore@3 and AssemblyInfo.cs

### ISSUE THREAD

**Issue by agilenut** [BMuuN/vsts-assemblyinfo-task#335]
I have a mixed solution with both .Net Core and .Net Framework projects. 

The [wiki overview](https://github.com/BMuuN/vsts-assemblyinfo-task/blob/b545cd5aa5d4cb6c3cadd8635e182e978e2942ae/src/Overview.md?plain=1#L46) page indicates that Assembly-Info-NetCore@3 will update .Net Core projects as well as .Net Framework AssemblyInfo.cs files. 

This is what I'd like to do. But I'm not seeing the version attributes get updated in the AssemblyInfo.cs files. I am using the `IgnoreNetFrameworkProjects: true` setting to ignore the warning. But that doesn't seem to be affecting the version numbers.

I also attempted to add `**/AssemblyInfo.cs` to the file paths but I got a warning stating the task only looked for csproj, vbproj, and prop files.

Any ideas what I might be missing?

**Comment by BMuuN** [comment]
Hey @agilenut the Assembly-Info-NetCore@3 task will only update .Net Core and .Net Standard project files.  If you have a .Net Framework project I suggest you use the task Assembly-Info-NetFramework@3.  You can find more info on the Task Parameters & Build Yaml](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Task-Parameters-&-Build-Yaml) wiki page.

Hope this helps.

**Comment by agilenut** [comment]
Thanks @BMuuN. Are you saying Assembly-Info-NetFramework@3 will update both framework and core projects or do I need to use both tasks for my solution which contains both?

Also it might be helpful to clarify the wiki page.

**Comment by BMuuN** [comment]
You will need to use both tasks.  I've update the wiki and README.md to match what's listed on the [marketplace](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task) 👍
