### ISSUE TITLE
Assembly Info Net Framewok is using EOL Node Version

### ISSUE THREAD

**Issue by thdudens** [BMuuN/vsts-assemblyinfo-task#368]
Hi Folks!

First of all - thank you all for maintaining this repo! 

As of this week, we receive the following warning in our azure pipeline (.Net Framework):
`##[warning]Task 'Assembly Info (.Net Framework)' version 3 (Assembly-Info-NetFramework@3) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance`

This warning does only appear in `Assembly-Info-Task@3` - the `Assembly-Info-NetCore@3` is running without a warning :)

**EDIT 2024-10-28:** 
Warning is now shown with `Assembly-Info-NetCore@3` as well

I wanted to ask if you are aware of this, if there will be an upgrade to a newer node version.

Thanks in advance for your answer.

Kind regards

**Comment by BMuuN** [comment]
Hey, thanks for getting I touch. I was not aware of this issue but I will take a look and make any amendments necessary.

**Comment by danspam** [comment]
We are using `Assembly-Info-NetCore@3` and are now experiencing this warning.

**Comment by m-soltani** [comment]
yes, I can confirm that both tasks are now throw warnings regarding node.js version deprecation.

**Comment by thdudens** [comment]
I can confirm as well - started to receive the warning now with the `Assembly-Info-NetCore@3`, too. 
Running on a MS-Hosted `windows-2022` agent

**Comment by guestdj** [comment]
I am also getting the warning in my build pipeline: 
```
Downloading task: Assembly-Info-NetFramework (3.3.0)
##[warning]Task 'Assembly Info (.Net Framework)' version 3 (Assembly-Info-NetFramework@3) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```
