### ISSUE TITLE
Attribute are inserted regardless of the 'Insert Attributes' switch

### ISSUE THREAD

**Issue by beatscholl** [BMuuN/vsts-assemblyinfo-task#39]
Hi, 
looks like a recent change ignores the 'Insert Attributes' flag.
Although set to false, the attributes are added in any case.

As we are splitting generic informations from assembly-specific information our builds fail now because of the duplicate attributes.

Immediate action would be highly appreciated.

**Comment by BMuuN** [comment]
Hi @beatscholl 

Apologies for this issue.  I've just pushed a new version (v1.1.38) which fixes the issue.  Do you want to run a build and check it's working your end?

**Comment by beatscholl** [comment]
This solves the problem! 
That was quick!
Thanks a lot!
