### ISSUE TITLE
Version 1.1.37 - Insert Attributes flag broken

### ISSUE THREAD

**Issue by ArjanThiele** [BMuuN/vsts-assemblyinfo-task#40]
Hi,

This morning I noticed that my build process was failing and it seems that the Insert Attributes flag is not working anymore. In the configuration the Insert Attribute flag is unchecked as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/39691559/40602732-fa3976be-6259-11e8-8503-685594e8096c.png)

In the log file below you can see that the Insert Attributes is logged as false but the process is still adding the attributes.

Can you look into this?
Thanks in advance!

> ##[section]Starting: Set Assembly Manifest Data
 ==============================================================================
 Task         : Assembly Info
 Description  : Set assembly information such as Version, Copyright and Trademark etc.
 Version      : 1.1.37
 Author       : Bleddyn Richards
 Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
 ==============================================================================
 Preparing task execution handler.
 Executing the powershell script: C:\vstsagent\A1\_work\_tasks\Assembly-Info-Task_3edc451e-360c-40e5-a221-a42d5c987ab8\1.1.37\ApplyAssemblyInfo.ps1
 AssemblyInfo.cs)
 Validating Version: 7.5.18148.1
 Validating File Version: 7.5.18148.1
 Validating Informational Version: 7.5.18148.1-release-ci
 Task Parameters:
 	Source Directory: C:\vstsagent\A1\_work\1\s\Code\Multisupport
 	Net Framework File: GlobalAssemblyInfo.cs
 	Net Framework File: AssemblyInfo.cs
 	Net Core File: 
 	Title: 
 	Product: 
 	Description: 
 	Company: 
 	Copyright: 
   	Trademark: 
   	Culture: 
   	Configuration: release-ci
   	Version: 7.5.18148.1
   	File Version: 7.5.18148.1
   	Informational Version: 7.5.18148.1
   **Insert Attributes: False**
   Setting .Net Framework assembly info...
  C:\vstsagent\A1\_work\1\s\Code\Multisupport\Assembly\BusinessService\Properties\AssemblyInfo.cs
 **Adding --> AssemblyVersion: 7.5.18148.1**
   AssemblyVersion: 7.5.18148.1
   **Adding --> AssemblyFileVersion: 7.5.18148.1**

**Comment by KenticoMartinS** [comment]
Hi,
we came across the same problem. It seems, that problem is in **NetFramework.ps1** in **ProcessNetFrameworkAttribute** function:
```powershell
Function ProcessNetFrameworkAttribute($File, $FileContent, $AttributeName, $Regex, $Value, [bool]$InsertAttributes) {

    if(![string]::IsNullOrWhiteSpace($Value)) {
        if ($InsertAttributes) {
            $FileContent = InsertAttribute -File $File -Content $FileContent -Name $AttributeName -Value $Value
        }
        $FileContent = ReplaceAttribute -Content $FileContent -Name $AttributeName -RegEx $Regex -Value $Value
    }

    return $FileContent;
}
```
I think the **InsertAttributes** is grabbed from parent script **ApplyAssemblyInfo.ps1** and its type is string so the if condition is incorrectly evaluated.

**Comment by BMuuN** [comment]
Apologies for this issue.  I've just pushed a new version (v1.1.38) which fixes the issue.  Do you want to run a build and check it's working your end?

**Comment by ArjanThiele** [comment]
Thanks! The issue is solved.
