### ISSUE TITLE
Check for System.Reflection

### ISSUE THREAD

**Issue by NeloBorcram** [BMuuN/vsts-assemblyinfo-task#48]
Hello,
Thank you very much for this extension.
Would it be possible to check if the AssemblyInfo.cs file already contains the using statement for System.Reflection?
In case someone removes the hardcoded Attributes the using statement appears to be of no use and ppl tend to remove it, yet after the Attributes are beeing added by this build task the build is going to fail.
And it's quite hard for ppl inexperienced in all the vsts buildsteps to figure out what went wrong.

thanks!!

**Comment by BMuuN** [comment]
Your request has been implemented in v2.0.65. Apologies for the delay implementing this change!

Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
