### ISSUE TITLE
csproj InformationalVersion

### ISSUE THREAD

**Issue by berhir** [BMuuN/vsts-assemblyinfo-task#49]
We use GitVersion and I started to use this build task to update the csproj files with the version generated by GitVersion. We also want to set the informational version to what GitVersion provides. But unfortunately the build fails with errors like this:
`'0.1.0-PullRequest.303+280.Branch.pull/303/merge.Sha.9762352d70935032b8c55bdcaac8bf994f936c4a' is not a valid version string.`

It turned out that your build task updates the `Version` property instead of the `InformationalVersion`. There is already an issue about this problem but you closed it: #24 

According to the [documentation ](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#packageversion) the `Version` property has to be a valid NuGet package version string. But there is also the `InformationalVersion` property that gets used to set the `AssemblyInformationalVersion` attribute (see [here](https://github.com/dotnet/sdk/blob/b73819e683af64bd19c961973c77b2239cd20e5d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L83)). If `InformationalVersion` is not set then the value of the `Version` property gets used (see [here](https://github.com/dotnet/sdk/blob/b73819e683af64bd19c961973c77b2239cd20e5d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L167)).

Can you take another look if it's not better to set the `InformationalVersion` instead of the NuGet package `Version` property? Thank you for your work!

**Comment by BMuuN** [comment]
The fix has been implemented in v2.0.65. Apologies for the delay implementing this change!

Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
