### ISSUE TITLE
Can mutiple Source Folders be specified per task?

### ISSUE THREAD

**Issue by pspattillo** [BMuuN/vsts-assemblyinfo-task#51]
I have exceptions within source folder that prevent me from specifying source folder. It would be great to have an "exclude option" but in lieu of that I could specify multiple source folders omitting the ones I want to exclude but I see no provision to specify multiple source folders. 

Is there any way, short of invoking the assemblyinfo task for each of the many source folders I wish to modify assemblyinfo files for?

I have seen related questions about multiple files but I haven't seen the question above posed in any issues.

**Comment by BMuuN** [comment]
There is no scope to support multiple source folders.  Having said that v2.0.65 now includes the ability to specify wildcard for source files which may address your issues.

This version is a re-write and therefore includes breaking changes. You should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
