### ISSUE TITLE
Hosted Linux / Hosted Ubuntu 1604

### ISSUE THREAD

**Issue by ramonduraes** [BMuuN/vsts-assemblyinfo-task#52]
The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by SeriousM** [comment]
This is an unacceptable situation. @BMuuN what's the ETA for fixing this issue?

**Comment by SeriousM** [comment]
Regarding to https://github.com/Microsoft/azure-pipelines-task-lib a powershell-based vsts-task only runs on windows.  A small excerpt from the readme:

## PowerShell Tasks
A task which automates Powershell technologies can be written with our Powershell SDK. These only run on Windows.

## TypeScript Tasks
Cross platform tasks are written in TypeScript. It is the preferred way to write tasks once.




It seems that either the author has to rewrite the task as node/typescript task or we can't use it on linux agents.

**Comment by danielthompson** [comment]
Why wouldn't a PowerShell task run on Linux? 

https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6

**Comment by SeriousM** [comment]
> Why wouldn't a PowerShell task run on Linux?

It's not the powershell task that doesn't run on linux, it's the marketplace pipeline task that is written in powershell which is not able to run on linux.

The problem lies exactly in this line: https://github.com/Microsoft/azure-pipelines-agent/blob/3e0e6dd0111fa53e72e42e4cf14f94ac379cba5a/src/Agent.Worker/TaskRunner.cs#L104

My workaround is to use the scripts here in a submodule and execute it with a powershell task.

**Comment by BMuuN** [comment]
The task is currently in the process of being re-written in TypeScript and will be available for preview soon.  I began the re-write sometime ago but due to personal issues I've not had the time to finish it.

**Comment by davenewza** [comment]
Look forward to the Linux-compatible task.  Anyone have a workaround for the interim?

**Comment by SeriousM** [comment]
> Look forward to the Linux-compatible task. Anyone have a workaround for the interim?

nope. you could call the scripts by yourself  but for now we just build on windows machines...

**Comment by SeriousM** [comment]
Here is a testscript that can help you setup the call yourself: https://github.com/BMuuN/vsts-assemblyinfo-task/blob/master/TestScript.ps1

**Comment by BMuuN** [comment]
First up: - my sincere apologies for the delay implementing this change!

Your request has been implemented in v2.0.65.  Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time for your teams:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
