### ISSUE TITLE
No handler found for Assembly Info

### ISSUE THREAD

**Issue by PedroC88** [BMuuN/vsts-assemblyinfo-task#54]
I'm getting the following error when running the task on a private computer.

> A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X86)'.

The message itself looks self explanatory, but I'm running the task on a Microsoft Windows 10 Pro (1803) x64 virtual machine. I don't have any pending updates to install so I'm unsure as to what is missing on the server that would cause this issue.

**Comment by PedroC88** [comment]
I found what triggers the issue, it was actually an error on my end, when I installed the new VM I accidentally installed the x86 agent instead of the x64. However, the entire build still worked (even using MSbuild x64), this Assembly Info is only task that broke because of that.

I believe this ticket should be kept open until support for x86 is added as there shouldn't be a reason this task doesn't work on x86 machines.

**Comment by BMuuN** [comment]
Thanks for the feedback. The extension has been re-written in Node.js and should therefore work for both x64 and x86 architecture.  Can you update to v2.0.65 and let us know if you are still facing this issue.

Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.
