### ISSUE TITLE
Informational Version

### ISSUE THREAD

**Issue by PhilPJL** [BMuuN/vsts-assemblyinfo-task#68]
Testing your extension on VS 2017 and VSTS.

I tried using the extension set up like this
![image](https://user-images.githubusercontent.com/271656/51265821-89019980-19b1-11e9-9455-01de43bd8a2e.png)

This results in 
![image](https://user-images.githubusercontent.com/271656/51265717-4c35a280-19b1-11e9-8d21-7c417de58977.png)

which is not what I expected.  Is there an issue or am I doing something wrong?
It looks like I have version 1.1.139.  Will V2 fix this?

**Comment by BMuuN** [comment]
Date transformations are only supported on the `Copyright` field.
For the various way you can set version numbers please see the following article: 
https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning

**Comment by PhilPJL** [comment]
As I understand it the AssemblyInformationalVersion attribute doesn't have to contain a version number it can be any string I choose

From [https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-versioning](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-versioning) 
_An informational version, which is a string that represents additional version information included for informational purposes only._

Any chance you can enable date transformations etc for this field?

Also I can't find V2 of your task in Azure DevOps.  What am I missing?

**Comment by PhilPJL** [comment]
Actually I've decided what you have works fine.  I was just used to getting the build label injected into the InformationalVersion which is useful because it's then displayed in file properties.

**Comment by BMuuN** [comment]
As mentioned on the [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning#build-number) the `Build number format` can include date transforms, such as:  `$(Build.DefinitionName)_$(date:yyyy).$(date:MM).$(date:dd)$(Rev:.r)`. You can then use this as a version number by referencing the build variable `$(Build.BuildNumber)`.  

The only field which directly supports date transforms is the `Copyright` field.  If you require the date transforms for any other field please raise a separate issue and I'll get it implemented on the next version for you.

Please note v2.0.65 has been released.  This upgrade is a breaking change and you should follow these steps to prevent any down-time: https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2
