### ISSUE TITLE
SetVersion for NET Core/Standard maked cspros file unusable

### ISSUE THREAD

**Issue by bernd70** [BMuuN/vsts-assemblyinfo-task#76]
Hi,

If I let the V2 NET Core/Standard task patch my csproj files the build of some assembly file fails.

The error output is: 

_C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(780,5): Error : The OutputPath property is not set for project 'Common.Test.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project._

The error message appears misleading because as soon as I disable the SetVersionInfo task it compiles just fine again.

The reason for the error is that the line _<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>_ is moved from the end of the file to line 3.

Please do fix that.

There are some more unexpected modifications:

1. The <?xml ...> tag is removed
2. &#xD; (CR) is added for an empty tag spanning two lines.
3. Whitespace before the trailing slash of empty tags is remove. However, this schould not be an issue.

Original file:

<?xml version="1.0" encoding="utf-8>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
...
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
...

Modified file:

<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"/>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
...
    <NuGetPackageImportStamp>&#xD;
    </NuGetPackageImportStamp>
...

Greets

**Comment by BMuuN** [comment]
Can you post the task output here and if possible could you include the contents of your `*.csproj` file.

**Comment by bernd70** [comment]
Bleddyn,

it appears something went wrong when I created the issue. I did post an excerpt of my csproj file. Let's try again:

The task output ist: [Taskoutput.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/2799087/Taskoutput.txt)

Original csproj File: [MyProject.csproj.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/2799092/MyProject.csproj.txt)

csproj File after SetVersionInfo: [MyProjectAfterSetVersionInfo.csproj.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/2799093/MyProjectAfterSetVersionInfo.csproj.txt)

Hope this helps.

Greets

**Comment by BMuuN** [comment]
I'm not at my desk right now but from briefly looking at your error output and the contents of your csproj file it looks as if you're using the. Net Core/Standard task to target a project built for the .Net Framework.

You may want to try the Assembly Info task for the. Net Framework.

**Comment by bernd70** [comment]
You are right. This is a .NET  Framework project.

How am I supposed to use the tasks when having both project types in a solution? I do specify **/*.csproj to traverse all project files and thought SetVersion task would automatically filter only the applicable files.

Maybe you could detect the project type. Maybe checking for _<Project Sdk="Microsoft.NET.Sdk">_ is sufficient.

At least the file should not be rewritten when no changes are applied. In my case only the xml structure is changed but no real version specific data is actually modified.

Greets

**Comment by BMuuN** [comment]
@bernd70 thanks for taking the time to respond!

I agree, I should be detecting project types and skip if it's a .Net Framework csproj file.  This should fix the issue when altering the XML structure so I've added this to the backlog as a priority.

To resolve your issue you can add both `Assembly Info (.Net Framework)` and `Assembly Info (.Net Core & .Net Standard)` tasks to your build pipeline just be sure to alter the file names to target only the files you wish to amend, for example, alter the `Assembly Info (.Net Core & .Net Standard)` to target only the following projects:  

![image](https://user-images.githubusercontent.com/2933934/51792828-0944ad80-21af-11e9-9987-8c39e57d8e70.png)

I'd also recommend enabling the `Write unicode BOM` option on the task, this will ensure your `utf-8` files will be saved as `utf-8`.  They're currently being saved as `iso-8859-1` as the byte order mark (BOM) is not written:
```
2019-01-25T23:14:57.8579220Z 	Detected character encoding: utf-8
2019-01-25T23:14:57.9191174Z 	Verify character encoding: iso-8859-1
```

Hope this helps and thanks again for the great feedback! 👍

**Comment by bernd70** [comment]
Yeah, I know to work around by specifying every single filename.

I could try to fix this in your code and create a pull request but I never created a VSTS extension so it will also take some time to dig into that. :-)

Thanks for the BOM hint. I changed the encoding to UTF-8 and Write-BOM for the task.
