### ISSUE TITLE
Bakslash on Mac OS Build

### ISSUE THREAD

**Issue by bernd70** [BMuuN/vsts-assemblyinfo-task#77]
Another issue: If I specify my files using a backslash (**\AssemblyInfo.cs) macOS will not find any files. I have to use a forward slash (**/AssemblyInfo.cs)

Greets

**Comment by BMuuN** [comment]
Ahh yes this is dependant on the build agent you use. I did debate removing the default file names however I left them in for guidance.

I'm going to close this as it's a non-issue, the backslash will work perfectly fine on a Windows agent.

I wasn't aware you could compile .Net Framework projects on a Mac.  I've never used a Mac so you'll have to excuse me on this one.

**Comment by bernd70** [comment]
Closing is okay for me since I have a way to work around.

Yes, we build a Xamarin.Forms project for iOS, that does not build on Windows.
