### ISSUE TITLE
Doesnt work for .net core 2.0

### ISSUE THREAD

**Issue by Seekeer** [BMuuN/vsts-assemblyinfo-task#81]
I got asp.net core 2 project:
![image](https://user-images.githubusercontent.com/2019187/52244454-bbd2e980-28ee-11e9-9d81-b131099294d3.png)

Build step setup is: 
![image](https://user-images.githubusercontent.com/2019187/52244501-f9377700-28ee-11e9-9dbe-472cb0b58509.png)

But when I start build in `Set Assembly Manifest Data` step I got:

	2019-02-04T23:30:23.9696475Z Processing: Z:\Dev\vsts-agent-win-x64-2.142.1\_work\4\s\FA\FAServer\FAServer.csproj
	2019-02-04T23:30:23.9747734Z 	Detected character encoding: utf-8
	2019-02-04T23:30:23.9770400Z ##[warning]	Skipping, project is not targeting .Net Core or .Net Standard

How could I fix that?

**Comment by BMuuN** [comment]
Can you post the content of `FAServer.csproj`

**Comment by k3flo** [comment]
I get the same error in Version "2.0.70". 
Version "2.0.67" worked as expected.

I have 
`<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup> 
<TargetFramework>netcoreapp2.1</TargetFramework> 
</PropertyGroup> 
</Project>`
in .csproj

**Comment by k3flo** [comment]
Here is the full projectfile:

[projectFile.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/2831681/projectFile.txt)

**Comment by k3flo** [comment]
I found the error in your code. You are checking
`if (result.Project.$.Sdk !== 'Microsoft.NET.Sdk') {`

but my sdk is "Microsoft.NET.Sdk.Web".

**Comment by BMuuN** [comment]
@k3flo and @Seekeer 

I've just pushed v2.0.73 of the extension which should fix both your issues.
Can you run a build and let me know if your issues have been resolved.

Thanks

**Comment by k3flo** [comment]
@BMuuN
Issue is resolved. Thank you

**Comment by BMuuN** [comment]
Closing as this issue has been resolved.
