### ISSUE TITLE
Yaml example request

### ISSUE THREAD

**Issue by binarysenator** [BMuuN/vsts-assemblyinfo-task#87]
I appreciate that you've demonstrated how to use your feature using the UI pipeline components, but for whatever reason my pipeline is locked into YAML mode only so I need an example of how to actually call your exension purely from YAML and I can't figure it out. I need the .NET Core task syntax please!

**Comment by BMuuN** [comment]
Please see issue #78 for an example configuration for a YAML pipeline.

FYI: to enable/disable YAML pipelines, from AzDO click your profile icon in the top right, select "Preview Features" from there you can enable/disable YAML pipeline by toggling the "New YAML pipeline creation experience" option.

**Comment by benrose-dca** [comment]
Thanks very much for that, works a charm!

**Comment by BMuuN** [comment]
No worries at all.  I'm closing this issue as I've added the YAML example to the [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Task-Parameters-Example#yaml).
