### ISSUE TITLE
Tooltip Change - Copyright

### ISSUE THREAD

**Issue by wgv-srsedate** [BMuuN/vsts-assemblyinfo-task#88]
![image](https://user-images.githubusercontent.com/37081224/52743587-f9470f00-2f9f-11e9-9e63-ae9ab6c1a183.png)

When viewing the tooltip for the **Copyright** field, you give an example that is no longer valid as of v2 of your task.  Instead of "$(date:yyyy)", it should use the proper example of "$(date:YYYY)".

I got this information from the Wiki regarding copyright changes between versions 1 and 2, at the link below.  I only raise this issue because the tooltip example had temporarily led me down the wrong path.

https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Copyright

**Comment by BMuuN** [comment]
Fixed in the next release.
