### ISSUE TITLE
Date Variables don't work in the Version Number fields

### ISSUE THREAD

**Issue by kellyelton** [BMuuN/vsts-assemblyinfo-task#89]
Version 2.0.73
.net Standard Project

`$(Date:yy).$(Date:MM).$(Date:dd).$(Build.BuildId)` in any version boxes don't replace the date variables, only the BuildId

**Comment by BMuuN** [comment]
Date transforms only work on the `Copyright` field.  Please see this wiki for examples on the supported date transformations:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Copyright

**Comment by kellyelton** [comment]
Is it a lot of work to make them work for all fields?

**Comment by BMuuN** [comment]
This is something I'm looking at for a future release.

**Comment by calloncampbell** [comment]
Any update on this functionality?

**Comment by BMuuN** [comment]
Date transforms have been added to all fields for both the Net Core and Net Framework tasks.
Please ensure you are running v2.1.91 of the extension.
