### ISSUE TITLE
File corrupted when setting Copyright with a value containing ©

### ISSUE THREAD

**Issue by Welchen** [BMuuN/vsts-assemblyinfo-task#97]
Tried to set my Copyright to "Copyright © $(CompanyName), $(CopyrightDate)" and each time I would get a couple of random characters at the top of my file which caused my build to fail.  Once I remembered the setting of that value the build would go fine.

**Comment by BMuuN** [comment]
Ensure `CompanyName` and `CopyrightDate` are variables in your build pipeline and try setting `File encoding` task parameter to `UTF-8` and tick the `Write unicode BOM` task parameter.

If that doesn't work can you post your build output...

**Comment by AlexGilliland** [comment]
Was able to reproduce the issue and doing the steps above resolved the issue for the failing builds.

**Comment by Welchen** [comment]
UTF-8 and Write Unicode changes fixed my issue. Thank you.

**Comment by BMuuN** [comment]
You're welcome both :) 
I knew it was a Unicode issue when you stated "random characters at the top of my file" 😉
